modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=""

[[mods]]
modId="tinkersnewlife_cursed"
version="${mod_version}"
displayName="匠魂新生·咒术"
description='''Tinker's Newlife: Cursed'''

[[dependencies.tinkersnewlife_cursed]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tinkersnewlife_cursed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"